
set(target "appRebirth")
set(working_dir "C:/Users/jayem/Documents/Rebirth")
set(src_and_dest_list
    "C:/Users/jayem/Documents/Rebirth/Main.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/Main.qml"
    "C:/Users/jayem/Documents/Rebirth/GameplayUI.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/GameplayUI.qml"
    "C:/Users/jayem/Documents/Rebirth/HitObject.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/HitObject.qml"
    "C:/Users/jayem/Documents/Rebirth/CustomFonts.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/CustomFonts.qml"
    "C:/Users/jayem/Documents/Rebirth/NotificationMessage.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/NotificationMessage.qml"
    "C:/Users/jayem/Documents/Rebirth/JudgementLine.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/JudgementLine.qml"
    "C:/Users/jayem/Documents/Rebirth/Trail.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/Trail.qml"
    "C:/Users/jayem/Documents/Rebirth/MapSelectMenu.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/MapSelectMenu.qml"
    "C:/Users/jayem/Documents/Rebirth/MapSelectSideMenu.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/MapSelectSideMenu.qml"
    "C:/Users/jayem/Documents/Rebirth/MapSelectSideMenuOptionBtn.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/MapSelectSideMenuOptionBtn.qml"
    "C:/Users/jayem/Documents/Rebirth/MapSelectTransition.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/MapSelectTransition.qml"
    "C:/Users/jayem/Documents/Rebirth/TitleScreen.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/TitleScreen.qml"
    "C:/Users/jayem/Documents/Rebirth/MapBackground.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/MapBackground.qml"
    "C:/Users/jayem/Documents/Rebirth/Results.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/Results.qml"
    "C:/Users/jayem/Documents/Rebirth/EmotionalCapacity.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/EmotionalCapacity.qml"
    "C:/Users/jayem/Documents/Rebirth/HoldNoteController.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/HoldNoteController.qml"
    "C:/Users/jayem/Documents/Rebirth/DoubleTapJudgementRing.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/DoubleTapJudgementRing.qml"
    "C:/Users/jayem/Documents/Rebirth/NoteShatterEffect.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/NoteShatterEffect.qml"
    "C:/Users/jayem/Documents/Rebirth/QmlSoundEffects.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/QmlSoundEffects.qml"
    "C:/Users/jayem/Documents/Rebirth/Stage.qml"
    "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/Rebirth/Stage.qml"

)
set(timestamp_file "C:/Users/jayem/Documents/Rebirth/build/Desktop_Qt_6_8_3_MinGW_64_bit-Release/.qt/appRebirth_qml.txt")
